config/routes.rb
Rails.application.routes.draw do
  root "pages#home"

  #Set up a route to the "about" page
  get "about", to: "pages#about"

  # At this point, if we add ':destroy' to the route set, we have exposed all of the
  # REST-ful routes. There's no longer a reason to limit them with the 'only' array, as
  # in the line below. So, use the equivalent set provided in the uncommented line.
  #
  # resources :articles, only: [:show, :index, :new, :create, :edit, :update, :destroy]
  #
  # REST is a mapping between CRUD and the HTTP verbs get, post, patch/put and delete.
  #
  resources :articles
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  validates :title, presence: true, length: { minimum: 1, maximum: 100 }
  validates :description, presence: true, length: { minimum: 10, maximum: 300 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]

  def show # show a particular article (see show.html.erb)
    # the route requires this show action to provide an Article id in the URL. It is
    # accessible, here, in the params array. @article gets the article object.
    # see 'set_article', below, and 'before_action', above.

  end

  def index # show all the articles (see index.html.erb)
    @arts = Article.all
  end

  def new # (1) show any errors which may have occurred in previous form submission
          # (2) make the form available again
    # 'new.html.erb' has the function of showing errors for the previous time someone 
    # attempted to create a new article in this session (see new.html.erb line 5). When
    # the user attempted to create an article, an @article instance param was created 
    # and its errors.full_messages is accessible from the @article instance var.
    # BUT, the first time through this action in this session, there is no @article 
    # instance param because there was no prior attempt to create an article IN THIS
    # SESSION. So, we create a happy @article here to make it available in the view 
    # and so that no error will occur when we attempt to access it.
    @article = Article.new
  end

  def edit
    # the route requires this edit action to provide an Article id in the URL. It is
    # accessible, here, in the params array. @article gets the article object.
    # see 'set_article', below, and 'before_action', above.
  end

  def create
    #REQUIRE that a valid article object is present (we rec'd it here from the form)
    #Then, from the required article object, PERMIT access to the title and description.
    #Finally, create a new Article object in the @article instance variable
    @article = Article.new(params_whitelist)

    # save the @article's data to the Articles table. If @article.save worked, then it
    # returns true and we are redirected to the 'show' action. If it failed, false is
    # returned and we are redirected to the 'new' action which will display the errors
    # that occurred and will display the title and description text entries.
    if @article.save
      flash[:notice] = "Article was successfully created and saved."

      #redirect to the 'show' article action we previously created in this controller, above.
      redirect_to @article # show the data stored in the just-saved article
    else
      # @article.save failed! So, return to the 'new' action to see the errors and try
      # again.
      render 'new' # Again, show the form to create an article
    end
  end

  def update
    # the route requires this update action to provide an Article id in the URL. It is
    # accessible, here, in the params array. @article gets the article object.
    # see 'set_article', below, and 'before_action', above.
   if @article.update(params_whitelist)
      flash[:notice] = "Article was successfully updated."
      redirect_to @article #as in 'create' above, this sends us to the 'show' action
    else
      render 'edit'
    end
  end

  def destroy
    # the route requires this DELETE action to provide an Article id in the URL. It is
    # accessible, here, in the params array. @article gets the article object.
    # see 'set_article', below, and 'before_action', above.

    # now, delete the article
    @article.destroy

    # where do we want to go after the @article is destroyed? The listing page.
    redirect_to articles_path
  end

  private

  def set_article
    @article = Article.find(params[:id])
  end

  def params_whitelist
    params.require(:article).permit(:title, :description)
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/articles/_form.html.erb
<% if @article.errors.any? %> 
  <h2>The following errors prevented the article from being saved</h2> 
  <ul> 
    <% @article.errors.full_messages.each do |msg| %> 
      <li><b><%= "(_form) " + msg %></b></li> 
    <% end %> 
  </ul>
  <br/>
<% end %>

<%= form_with( model: @article, local: true ) do |f| %>

  <p>
    <%= f.label :title %><br/>
    <%= f.text_field :title %>
  </p>

  <p>
    <%= f.label :description %><br/>
    <%= f.text_area :description %>
  </p>

  <p>
    <%= f.submit %>
  </p>

<% end %>

app/views/articles/edit.html.erb
<h1>Edit an Existing Article</h1>

<%= render 'form' %>

<p style="font-color:red; font-family:Trebuchet MS;font-size:16px;">
  <%= link_to 'Cancel this Edit and List all Articles', articles_path %>
</p>

app/views/articles/index.html.erb
<h1>Articles listing page</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>  
      <th>Description</th>
      <th colspan='3'>Actions</th>
    </tr>
  </thead>

  <style>
    .tdLink {
      text-decoration: none; 
      font-color:red; 
      font-family:Trebuchet MS;
      font-size:13px;
    } 
    td, th{
      padding: 0 30px 0 0;
      text-align: left;
    }
  </style>
  <tbody>
    <% @arts.each do |art| %>
      <tr>
        <td><%= art.title %></td>
        <td><%= art.description %></td>
        <td class='tdLink'><%= link_to 'Show', article_path(art) %></td>
        <td class='tdLink'><%= link_to 'Edit', edit_article_path(art) %></td>
        <td class='tdLink'><%= link_to 'Delete', article_path(art), method: :Delete, data: { confirm: "Delete this article?" } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<p style="font-color:red; font-family:Trebuchet MS;font-size:16px;">
  <%= link_to 'Create a New Article', new_article_path %><br/>
  <style>
    img {
      width: 45px;
      margin-top: 10px;
    }
  </style>
  <%= link_to root_path do %>
    <%= image_tag('homeIcon.png') %>
  <% end %>
</p>

app/views/articles/new.html.erb
<h1>Create a NEW Article</h1>

<%= render 'form' %>

<p style="font-color:red; font-family:Trebuchet MS;font-size:16px;">
  <%= link_to 'List all Articles', articles_path %>
</p>

app/views/articles/show.html.erb
<h1>
  Show Article Details, baby.
</h1>

<h3><b>Title:</b>&nbsp;<font color='red'><%= @article.title %></font></h3>
<h3><b>Description:</b>&nbsp;<font color='blue'><%= @article.description %></font></h3>

<STYLE>P,A {text-decoration: none;} </STYLE>

<p style="font-color:red; font-family:Trebuchet MS;font-size:16px;">
  <%= link_to 'List All Articles', articles_path %> |
  <%= link_to 'Edit This Article', edit_article_path(@article) %> |
  <%= link_to 'Delete This Article', article_path(@article), method: :delete, data: { confirm: "Delete this article?" } %>
</p>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <%= msg %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AlphaBlog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/messages' %>
    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<h1>This page is what it's all ABOUT, dude!</h1>

<%= link_to 'Home Page', root_path %>

app/views/pages/home.html.erb
<html>
  <head>
    <title>Title of the document</title>
    <style> 
    </style>
  </head>
  <body>
    <h1>
      Hello from the Home page route
    </h1>
    <h2>(Thank you, Mashrur!)</h2>
  </body>

  <%= link_to 'List of Articles', articles_path %><br/>
  <%= link_to 'About Page', about_path %>


</html>